### ISSUE TITLE
Import mxnet throws libcudart error on non cuda linux hosts

### ISSUE THREAD

**Issue by vdantu** [awslabs/mxnet-model-server#390]
I am seeing 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mxnet-model-server/testenv/local/lib/python2.7/site-packages/mxnet/__init__.py", line 25, in <module>
    from . import engine
  File "/mxnet-model-server/testenv/local/lib/python2.7/site-packages/mxnet/engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "/mxnet-model-server/testenv/local/lib/python2.7/site-packages/mxnet/base.py", line 113, in <module>
    _LIB = _load_lib()
  File "/mxnet-model-server/testenv/local/lib/python2.7/site-packages/mxnet/base.py", line 105, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory
```

When I try to `import mxnet` after doing a pip install from setup.py. This happens when I try to import "mxnet" in my python module. This doens't happen with mxnet-mkl and happens with mxnet-cu90mkl package on generic linux host.  We might need to change the default installation for linux.

Steps to recreate this issue on a linux machine: 
```
1. (testenv)$ pip install mxnet-cu90mkl
2. (testenv)$ python
3.  >>> import mxnet
```

**Comment by vrakesh** [comment]
resolved in  PR #394

**Comment by Karna829** [comment]
Solution  :
1. deactivate the environment 
2. edit ~/.bashrc file the LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH and save
3. type the command ``` source ~/.bashrc```
4. sudo ldconfig to reflect the changes for library to be seen by OS
5. done! activate the environment 
6. import mxnet 
Problem solved. I spent 1 whole day find the solution...
